name: Java Maven Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java (latest version)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify your required Java version here (e.g., 11, 17)

      # Install dependencies and build project
      - name: Install dependencies and build
        run: mvn install --no-transfer-progress
