name: Java Maven Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          app_token: ${{secrets.IR_API_KEY}}
      # ============= InvisiRisk Setup End =============
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java (latest version)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify your required Java version here (e.g., 11, 17)

      # Install dependencies and build project
      - name: Install dependencies and build
        run: mvn install --no-transfer-progress
      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============