name: Java Maven Build with InvisiRisk PSE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          app_token: ${{ secrets.IR_API_KEY }}
      # ============= InvisiRisk Setup End =============

      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK with Adoptium (formerly AdoptOpenJDK)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify your Java version
          distribution: 'temurin'  # Correct distribution for Adoptium (formerly AdoptOpenJDK)

      # Install dependencies and build with Maven
      - name: Install dependencies and build
        run: mvn install --no-transfer-progress

      # Run tests
      - name: Run tests
        run: mvn test

      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============
